### ISSUE TITLE
Improve error handling 

### ISSUE THREAD

**Issue by roncewind** [Senzing/redoer#114]
When processing records for a 20M test run in AWS I found a couple of instances where we received the following in the logs
```
2022-04-27 20:14:34,806 senzing-50100830E G2Engine.process() error. Redo Record: 
{
    "REASON": "LIB_FEAT_ID[119128092] of FTYPE_ID[13] went generic for CANDIDATES AND SCORING ECLASS_ID[1] in LENS_ID[1]",
    "DATA_SOURCE": "TEST",
    "RECORD_ID": "604956152",
    "ENTITY_TYPE": "GENERIC",
    "DSRC_ACTION": "X"
}
; Error: (G2Exception(...), '-1|UNKNOWN ERROR')
Exception in thread Process-0-ProcessReadFromSqsThread-2:
Traceback (most recent call last):
  File "/app/redoer.py", line 2072, in process_redo_record
    self.g2_engine.process(redo_record)
  File "/opt/senzing/g2/python/senzing/G2Engine.py", line 322, in process
    raise TranslateG2ModuleException(tls_var.buf.value)
senzing.G2Exception.G2Exception: (G2Exception(...), '-1|UNKNOWN ERROR')
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/app/redoer.py", line 2702, in run
    process_succeeded = self.process_redo_record(redo_record)
  File "/app/redoer.py", line 2084, in process_redo_record
    if is_db_connection_error(err.args[0]):
  File "/app/redoer.py", line 3044, in is_db_connection_error
    return 'Database Connection Failure' in errorText or 'Database Connection Lost' in errorText
TypeError: argument of type 'G2Exception' is not iterable
```

Looks like we can improve our error handling here:

https://github.com/Senzing/redoer/blob/cd54bcddbe32f35019496c77f314ad95865bfb3d/redoer.py#L2084-L2086

**Comment by docktermj** [comment]
In lines like 

https://github.com/Senzing/redoer/blob/cc18c2e7c3c6d505224d3000039e62469b3323b4/redoer.py#L2152

The `err.args[]` method is used to check for the connection error.  This is incorrect.   It bypasses the "stringifying" method at

https://github.com/Senzing/g2-sdk-python/blob/e3e4b2dd9f7ad4498c70dc90a73dd6be13e31637/src/senzing/G2Exception.py#L38-L46

So the 3 instances of calling `is_db_connection_error(err.args[0])` should be replaced with

```python
is_db_connection_error(str(err))
```

**Comment by docktermj** [comment]
A test program

```python
#! /usr/bin/env python3


def is_in(athingee):
    return "Bob" in athingee


def try_except(mythingee):
    try:
        if is_in(mythingee):
            print("Bob was here")
        else:
            print("Bob wasn't here")
    except Exception as err:
        print("Bob had an exception")

try_except("Bob")
try_except("bob")
try_except(Exception("bob2"))
try_except(str(Exception("bob3")))

print(is_in(str(Exception("bob4"))))
print(is_in(Exception("bob5")))
```
Results:
```
Bob was here
Bob wasn't here
Bob had an exception
Bob wasn't here
False
Traceback (most recent call last):
  File "./test.py", line 23, in <module>
    print(is_in(Exception("bob5")))
  File "./test.py", line 5, in is_in
    return "Bob" in athingee
TypeError: argument of type 'Exception' is not iterable
```

**Comment by docktermj** [comment]
Pull Requests:

- https://github.com/Senzing/redoer/pull/261
